name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: install
        run: |
          yarn install
      - name: build
        run: |
          yarn build
        env:
          NEXT_PUBLIC_GITHUB_PAGES: true
      - name: generate sitemap
        run: |
          npx next-sitemap
      - name: Create .nojekyll
        run: |
          touch out/.nojekyll
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
